TOPLEVEL_LANG ?= verilog
SIM ?= icarus
VERILOG_SOURCES = $(shell pwd)/clocks.sv
TOPLEVEL := top # Verilog or SystemVerilog TOP file module name
MODULE   := clocks_tb # Python file name
 
 
include $(shell cocotb-config --makefiles)/Makefile.sim