TOPLEVEL_LANG ?= verilog
SIM ?= icarus
VERILOG_SOURCES = $(shell pwd)/mux8x1.sv
TOPLEVEL := mux # Verilog or SystemVerilog TOP file module name
MODULE   := mux8x1_tb # Python file name
 
 
include $(shell cocotb-config --makefiles)/Makefile.sim