TOPLEVEL_LANG ?= verilog
SIM ?= icarus
VERILOG_SOURCES = $(shell pwd)/ram8b.sv
TOPLEVEL := top # Verilog or SystemVerilog TOP file module name
MODULE   := ram8b_tb # Python file name
 
 
include $(shell cocotb-config --makefiles)/Makefile.sim