TOPLEVEL_LANG ?= verilog
SIM ?= icarus
VERILOG_SOURCES = $(shell pwd)/pr_enc.sv
TOPLEVEL := top # Verilog or SystemVerilog TOP file module name
MODULE   := pr_enc_tb # Python file name
 
 
include $(shell cocotb-config --makefiles)/Makefile.sim